If You Are Executing this With Sudo
* That's good too.

diff --git a/ybacklight b/ybacklight
--- a/ybacklight
+++ b/ybacklight
@@ -8,8 +8,8 @@ set_raw_brightness() {
     if [ $1 -ge $min_brightness ] && [ $1 -le $max_brightness ]
     then
         sudo -n ls > /dev/null 2>&1
-        if [ "$?" -ne 0 ]; then
-            echo 'Passwordless sudo privileges are required'
+        if [ "$?" -ne 0 ] || [ "$UID" -ne 0 ]; then
+            echo 'Root user privilege or passwordless sudo permission is required'
             exit
         fi
         sudo bash -c "echo $1 | tee $brightness_file"
